// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicSoon,
  DefaultSoonProps
} from "./plasmic/jungle_fever/PlasmicSoon";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface SoonProps extends Omit<DefaultSoonProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultSoonProps altogether and have
// total control over the props for your component.
export interface SoonProps extends DefaultSoonProps {}

function Soon_(props: SoonProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicSoon to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicSoon are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all SoonProps here, but feel free
  // to do whatever works for you.

  return <PlasmicSoon root={{ ref }} {...props} />;
}

const Soon = React.forwardRef(Soon_);
export default Soon;
