// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: neKnaqAFQgtkJjtbXthdKd
// Component: ODTH0GNSW1H
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: -5kvBjMJU6nse/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import TextInput from "../../TextInput"; // plasmic-import: _oRzGL_a2z00t/component
import Button from "../../Button"; // plasmic-import: TmMHvKz8624iV/component
import Footer from "../../Footer"; // plasmic-import: LYimf7BcZyc4G/component

import { useScreenVariants as useScreenVariantsw2FpJ6DWBvL } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: W2fpJ_6d-WBvL/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_jungle_fever.module.css"; // plasmic-import: neKnaqAFQgtkJjtbXthdKd/projectcss
import sty from "./PlasmicSoon.module.css"; // plasmic-import: ODTH0GNSW1H/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: 9x2RT-jPTsI_B4/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: QIFkDJ_ce_gClo/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: wIv3yetKUg72by/icon

export type PlasmicSoon__VariantMembers = {};

export type PlasmicSoon__VariantsArgs = {};
type VariantPropType = keyof PlasmicSoon__VariantsArgs;
export const PlasmicSoon__VariantProps = new Array<VariantPropType>();

export type PlasmicSoon__ArgsType = {};
type ArgPropType = keyof PlasmicSoon__ArgsType;
export const PlasmicSoon__ArgProps = new Array<ArgPropType>();

export type PlasmicSoon__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  section?: p.Flex<"section">;
  textBox?: p.Flex<"div">;
  amountInput?: p.Flex<typeof TextInput>;
  play?: p.Flex<typeof Button>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultSoonProps {
  className?: string;
}

function PlasmicSoon__RenderFunc(props: {
  variants: PlasmicSoon__VariantsArgs;
  args: PlasmicSoon__ArgsType;
  overrides: PlasmicSoon__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsw2FpJ6DWBvL()
  });

  return (
    <React.Fragment>
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox___2ZNPe)}>
              <p.Stack
                as={"section"}
                data-plasmic-name={"section"}
                data-plasmic-override={overrides.section}
                hasGap={true}
                className={classNames(projectcss.all, sty.section)}
              >
                <Reveal
                  className={classNames("__wab_instance", sty.reveal__sbXqu)}
                  delay={500 as const}
                  duration={5000 as const}
                  triggerOnce={true}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kx5Qe)}
                  >
                    <div
                      data-plasmic-name={"textBox"}
                      data-plasmic-override={overrides.textBox}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.textBox
                      )}
                    >
                      {"Coming soon."}
                    </div>
                  </div>
                </Reveal>

                {true ? (
                  <TextInput
                    data-plasmic-name={"amountInput"}
                    data-plasmic-override={overrides.amountInput}
                    className={classNames("__wab_instance", sty.amountInput)}
                    name={"amountInput" as const}
                  />
                ) : null}
              </p.Stack>

              <Reveal
                className={classNames("__wab_instance", sty.reveal__gihc5)}
                delay={6000 as const}
                direction={"vertical" as const}
                duration={1500 as const}
                effect={"fade" as const}
                triggerOnce={true}
              >
                {true ? (
                  <Button
                    data-plasmic-name={"play"}
                    data-plasmic-override={overrides.play}
                    className={classNames("__wab_instance", sty.play)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xopq
                      )}
                    >
                      {"Watch"}
                    </div>
                  </Button>
                ) : null}

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lXmJs
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    {
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__hn7Iw
                        )}
                        href={
                          "https://foundation.app/collection/mholefnc" as const
                        }
                        target={"_blank" as const}
                      >
                        {"Foundation"}
                      </a>
                    }
                    <React.Fragment>{" | "}</React.Fragment>
                    {
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__qhJw
                        )}
                        href={
                          "https://opensea.io/collection/music-hole-ai-jungle-fever-fnc" as const
                        }
                      >
                        {"OpenSea"}
                      </a>
                    }
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </Reveal>
            </div>
          ) : null}

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "section",
    "textBox",
    "amountInput",
    "play",
    "footer"
  ],
  header: ["header"],
  section: ["section", "textBox", "amountInput"],
  textBox: ["textBox"],
  amountInput: ["amountInput"],
  play: ["play"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  section: "section";
  textBox: "div";
  amountInput: typeof TextInput;
  play: typeof Button;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSoon__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSoon__VariantsArgs;
    args?: PlasmicSoon__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSoon__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSoon__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSoon__ArgProps,
          internalVariantPropNames: PlasmicSoon__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSoon__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSoon";
  } else {
    func.displayName = `PlasmicSoon.${nodeName}`;
  }
  return func;
}

export const PlasmicSoon = Object.assign(
  // Top-level PlasmicSoon renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    section: makeNodeComponent("section"),
    textBox: makeNodeComponent("textBox"),
    amountInput: makeNodeComponent("amountInput"),
    play: makeNodeComponent("play"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicSoon
    internalVariantProps: PlasmicSoon__VariantProps,
    internalArgProps: PlasmicSoon__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSoon;
/* prettier-ignore-end */
